### ISSUE TITLE
upvoty - review images

### ISSUE THREAD

**Issue by ricardobrg** [tiki/upvoty#16]
As a developer I should use style lib icons for images that are vectors and all versions of image densities for the other images

Acceptance criteria
1 - Create the vector icons for the lib
2 - Create the missing image sizes

**Comment by ricardobrg** [comment]
no images left, just icons

**Comment by sfaria27** [comment]
@ricardobrg to add screenshot

**Comment by ricardobrg** [comment]
<img width="349" alt="Captura de Tela 2022-04-22 às 12 00 27" src="https://user-images.githubusercontent.com/8357343/164741005-94ccd3b1-ce6e-4b36-89a4-e163513895bf.png">
